[workspace]
resolver = "2"
members = ["entry", "cargo-xbuild"]
exclude = []

[workspace.dependencies]
crate_a = { path = "crates/crate_a", default-features = false }
crate_net = { path = "crates/crate_net" }