[workspace]
resolver = "2"
members = ["crates/crate_smp",
    "entry",
    "xtask",
]
exclude = []

[workspace.dependencies]
crate_a = { path = "crates/crate_a" }
crate_b = { path = "crates/crate_b" }
crate_smp = { path = "crates/crate_smp" }